"use client";

import { Image as ImageIcon, Sparkles, Type, Upload } from "lucide-react";
import { useEffect, useRef, useState } from "react";

const sections = ["Enquadramento", "Escolhas linguísticas", "Omissões", "Recursos emocionais", "Técnicas identificadas"] as const;
type Analysis = Record<(typeof sections)[number], string> & { ConteúdosRelacionados?: string };

export function ConsultAi() {
  const [text, setText] = useState(""); const [image, setImage] = useState<{ data: string; mimeType: string } | null>(null); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [quota, setQuota] = useState({ used: 0, limit: 5 }); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { void fetch("/api/ai/usage").then((response) => response.ok ? response.json() : null).then((value) => value && setQuota(value)); }, []);
  function chooseImage(file: File | undefined) { if (!file) return; if (!file.type.startsWith("image/") || file.size > 7 * 1024 * 1024) { setMessage("Escolha uma imagem de até 7 MB."); return; } const reader = new FileReader(); reader.onload = () => setImage({ data: String(reader.result).split(",")[1] ?? "", mimeType: file.type }); reader.readAsDataURL(file); }
  async function runAnalysis() { if ((!text.trim() && !image) || pending) return; setPending(true); setMessage(null); setAnalysis(null); try { const response = await fetch("/api/ai/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, image }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Não foi possível concluir a análise."); setAnalysis(data.analysis); setQuota(data.usage); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível concluir a análise."); } finally { setPending(false); } }
  return <div className="consult-ai-layout"><section className="ai-input"><div className="segmented" role="tablist" aria-label="Tipo de análise"><button className="segment active" type="button"><Type size={16} /> Texto</button><button className="segment" type="button" onClick={() => fileRef.current?.click()}><ImageIcon size={16} /> Imagem</button><button className="segment" type="button" onClick={() => fileRef.current?.click()}><Upload size={16} /> Upload</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={(event) => chooseImage(event.target.files?.[0])} /></div><div className="panel analysis-box"><textarea value={text} maxLength={4000} onChange={(event) => setText(event.target.value)} placeholder="Cole aqui o conteúdo que deseja analisar..." aria-label="Conteúdo para análise" />{image && <p className="selected-media">Imagem pronta para análise.</p>}<div className="analysis-footer"><span className="quota"><strong>{Math.max(0, quota.limit - quota.used)} de {quota.limit}</strong> análises disponíveis nesta semana · {text.length}/4000</span><button className="primary-button" disabled={(!text.trim() && !image) || pending || quota.used >= quota.limit} onClick={() => void runAnalysis()}><Sparkles size={16} />{pending ? "Analisando..." : "Analisar"}</button></div>{message && <p className="form-error">{message}</p>}</div></section><section aria-labelledby="result-title"><div className="panel-heading"><h2 id="result-title">Resultado da análise</h2></div><div className="accordion-list">{sections.map((title) => <details className="accordion" key={title} open={Boolean(analysis)}><summary>{title}</summary><p>{analysis?.[title] ?? "A análise aparecerá aqui."}</p></details>)}{analysis?.ConteúdosRelacionados && <details className="accordion" open><summary>Conteúdos relacionados</summary><p>{analysis.ConteúdosRelacionados}</p></details>}</div></section></div>;
}
