import { FlaskConical, Save } from "lucide-react";
import { CONTENT_STATUSES } from "@/domain/content/entities";
import { contentRepository } from "@/infrastructure/repositories/firebase-content-repository";
import { laboratoryRepository } from "@/infrastructure/repositories/firebase-laboratory-repository";
import { contentAttachmentRepository } from "@/infrastructure/repositories/firebase-content-attachment-repository";
import { ContentAttachmentsField } from "@/components/admin/content-attachments-field";
import { createLaboratory, updateLaboratory } from "./actions";

export const dynamic = "force-dynamic";
const statusLabel = { draft: "Rascunho", published: "Publicado", unpublished: "Despublicado", scheduled: "Agendado" } as const;

export default async function LaboratoryAdminPage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const { edit } = await searchParams;
  const laboratories = await laboratoryRepository.listLaboratories();
  const courses = await contentRepository.listCourses();
  const lessonOptions = (await Promise.all(courses.map(async (course) => { const modules = await contentRepository.listModules(course.id); return (await Promise.all(modules.map(async (module) => (await contentRepository.listLessons(module.id)).map((lesson) => ({ ...lesson, courseTitle: course.title, moduleTitle: module.title }))))).flat(); }))).flat();
  const selected = edit ? laboratories.find((laboratory) => laboratory.id === edit) : null;
  const attachments = selected ? await contentAttachmentRepository.list("laboratory", selected.id) : [];
  return <div className="admin-page content-admin-page"><header className="page-heading"><div><span className="kicker">Conteúdo expandido</span><h1>Laboratório</h1><p>Exercícios de análise para transformar aulas em prática.</p></div></header><details className="panel cms-settings" open={!selected}><summary><FlaskConical size={17} />Novo laboratório</summary><LaboratoryForm action={createLaboratory} lessons={lessonOptions} /></details><section className="laboratory-admin-list">{laboratories.length === 0 && <div className="panel empty-result">Nenhum laboratório cadastrado.</div>}{laboratories.map((laboratory) => <details className="panel laboratory-admin-card" open={selected?.id === laboratory.id} key={laboratory.id}><summary><span className="content-symbol"><FlaskConical size={19} /></span><span><strong>{laboratory.title}</strong><small>{laboratory.questions.length} perguntas · {statusLabel[laboratory.status]}</small></span></summary>{selected?.id === laboratory.id && <LaboratoryForm action={updateLaboratory} item={laboratory} lessons={lessonOptions} attachments={attachments} />}</details>)}</section></div>;
}

type LessonOption = { id: string; title: string; courseTitle: string; moduleTitle: string };
function LaboratoryForm({ action, item, lessons, attachments }: { action: (formData: FormData) => void; item?: Awaited<ReturnType<typeof laboratoryRepository.listLaboratories>>[number]; lessons: LessonOption[]; attachments?: Awaited<ReturnType<typeof contentAttachmentRepository.list>> }) { return <form className="cms-form form-grid" action={action} encType="multipart/form-data"><input type="hidden" name="laboratoryId" value={item?.id ?? ""} /><label>Título<input name="title" defaultValue={item?.title} required minLength={3} /></label><label>Slug<input name="slug" defaultValue={item?.slug} /></label><label className="full-field">Descrição<textarea name="description" defaultValue={item?.description} rows={3} /></label><label className="full-field">Caso analisado<textarea name="caseText" defaultValue={item?.caseText} rows={8} required /></label><label>Fonte<input name="source" defaultValue={item?.source} /></label><label>Tags, separadas por vírgula<input name="tags" defaultValue={item?.tags.join(", ")} /></label><label className="full-field">Perguntas, uma por linha<textarea name="questions" defaultValue={item?.questions.map((question) => question.prompt).join("\n")} rows={5} required /></label><label className="full-field">Análise oficial<textarea name="officialAnalysis" defaultValue={item?.officialAnalysis} rows={8} required /></label><fieldset className="material-picker full-field"><legend>Aulas relacionadas</legend>{lessons.map((lesson) => <label className="material-option" key={lesson.id}><input type="checkbox" name="lessonIds" value={lesson.id} defaultChecked={item?.lessonIds.includes(lesson.id)} /><span><strong>{lesson.title}</strong><small>{lesson.courseTitle} · {lesson.moduleTitle}</small></span></label>)}</fieldset>{item && <label>Status<select name="status" defaultValue={item.status}>{CONTENT_STATUSES.map((value) => <option key={value} value={value}>{value === "draft" ? "Rascunho" : value === "published" ? "Publicado" : value === "unpublished" ? "Despublicado" : "Agendado"}</option>)}</select></label>}<ContentAttachmentsField attachments={attachments} /><div className="form-actions"><button className="primary-button" type="submit"><Save size={16} />{item ? "Salvar laboratório" : "Criar rascunho"}</button></div></form>; }
