import { BookOpen, Save } from "lucide-react";
import { requireAdministrativeUser } from "@/application/access/session";
import { assertCanManageContent } from "@/application/content/permissions";
import { CONTENT_STATUSES } from "@/domain/content/entities";
import { REFERENCE_TYPES } from "@/domain/library/references";
import { contentRepository } from "@/infrastructure/repositories/firebase-content-repository";
import { caseRepository } from "@/infrastructure/repositories/firebase-case-repository";
import { referenceRepository } from "@/infrastructure/repositories/firebase-reference-repository";
import { createReference, updateReference } from "./actions";

export const dynamic = "force-dynamic";
const typeLabel = { livro: "Livro", artigo: "Artigo", filme: "Filme", documentário: "Documentário", discurso: "Discurso", bibliografia: "Bibliografia" } as const;
const statusLabel = { draft: "Rascunho", published: "Publicado", unpublished: "Despublicado", scheduled: "Agendado" } as const;

export default async function ReferencesAdminPage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const user = await requireAdministrativeUser(); assertCanManageContent(user);
  const { edit } = await searchParams;
  const [references, courses, cases] = await Promise.all([referenceRepository.listReferences(), contentRepository.listCourses(), caseRepository.listCases()]);
  const lessonOptions = (await Promise.all(courses.map(async (course) => { const modules = await contentRepository.listModules(course.id); return (await Promise.all(modules.map(async (module) => (await contentRepository.listLessons(module.id)).map((lesson) => ({ ...lesson, courseTitle: course.title, moduleTitle: module.title }))))).flat(); }))).flat();
  const selected = edit ? references.find((reference) => reference.id === edit) : null;
  return <div className="admin-page content-admin-page"><header className="page-heading"><div><span className="kicker">Conteúdo expandido</span><h1>Biblioteca</h1><p>Livros e referências para aprofundar a investigação.</p></div></header><details className="panel cms-settings" open={!selected}><summary><BookOpen size={17} />Nova referência</summary><ReferenceForm action={createReference} lessons={lessonOptions} cases={cases} /></details><section className="reference-admin-list">{references.length === 0 && <div className="panel empty-result">Nenhuma referência cadastrada.</div>}{references.map((reference) => <details className="panel reference-admin-card" open={selected?.id === reference.id} key={reference.id}><summary><span className="content-symbol"><BookOpen size={19} /></span><span><strong>{reference.title}</strong><small>{typeLabel[reference.type]} · {statusLabel[reference.status]}</small></span></summary>{selected?.id === reference.id && <ReferenceForm action={updateReference} item={reference} lessons={lessonOptions} cases={cases} />}</details>)}</section></div>;
}

type LessonOption = { id: string; title: string; courseTitle: string; moduleTitle: string };
type CaseOption = { id: string; title: string };
function ReferenceForm({ action, item, lessons, cases }: { action: (formData: FormData) => void; item?: Awaited<ReturnType<typeof referenceRepository.listReferences>>[number]; lessons: LessonOption[]; cases: CaseOption[] }) { return <form className="cms-form form-grid" action={action}><input type="hidden" name="referenceId" value={item?.id ?? ""} /><label>Título<input name="title" defaultValue={item?.title} required /></label><label>Autor<input name="author" defaultValue={item?.author} /></label><label>Tipo<select name="type" defaultValue={item?.type ?? "livro"}>{REFERENCE_TYPES.map((value) => <option key={value} value={value}>{typeLabel[value]}</option>)}</select></label><label className="full-field">Capa ou imagem<input name="coverUrl" type="url" defaultValue={item?.coverUrl} placeholder="https://..." /></label><label className="full-field">Descrição<textarea name="description" defaultValue={item?.description} rows={4} /></label><label>Tags, separadas por vírgula<input name="tags" defaultValue={item?.tags.join(", ")} /></label><label>Link de referência<input name="referenceUrl" type="url" defaultValue={item?.referenceUrl} /></label><fieldset className="material-picker full-field"><legend>Aulas relacionadas</legend>{lessons.map((lesson) => <label className="material-option" key={lesson.id}><input type="checkbox" name="lessonIds" value={lesson.id} defaultChecked={item?.lessonIds.includes(lesson.id)} /><span><strong>{lesson.title}</strong><small>{lesson.courseTitle} · {lesson.moduleTitle}</small></span></label>)}</fieldset><fieldset className="material-picker full-field"><legend>Casos relacionados</legend>{cases.map((referenceCase) => <label className="material-option" key={referenceCase.id}><input type="checkbox" name="caseIds" value={referenceCase.id} defaultChecked={item?.caseIds.includes(referenceCase.id)} /><span><strong>{referenceCase.title}</strong><small>Arquivo Trevas</small></span></label>)}</fieldset>{item && <label>Status<select name="status" defaultValue={item.status}>{CONTENT_STATUSES.map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></label>}<div className="form-actions"><button className="primary-button" type="submit"><Save size={16} />{item ? "Salvar referência" : "Criar rascunho"}</button></div></form>; }
