import { NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/application/access/session";
import { hasActiveEntitlement, hasAdministrativeAccess } from "@/application/access/permissions";
import { aiUsageRepository } from "@/infrastructure/repositories/firebase-ai-usage-repository";
import { randomUUID } from "node:crypto";

async function authorized() { const user = await getAuthenticatedUser(); if (!user || (!hasAdministrativeAccess(user.roles) && !hasActiveEntitlement(user.entitlement))) return null; return user; }
export async function GET() { const user = await authorized(); if (!user) return NextResponse.json({ error: "Não autenticado." }, { status: 401 }); return NextResponse.json(await aiUsageRepository.get(user.id)); }
export async function POST(request: Request) { const user = await authorized(); if (!user) return NextResponse.json({ error: "Não autenticado." }, { status: 401 }); const body = await request.json().catch(() => ({})); const action = String(body.action ?? ""); try { if (action === "reserve") { const usage = await aiUsageRepository.reserve(user.id); const reservationId = randomUUID(); await aiUsageRepository.complete(user.id, reservationId, { promptChars: 0, responseChars: 0, model: "gemini-3.5-flash" }); return NextResponse.json({ reservationId, usage }); } if (action === "complete" || action === "refund") { if (action === "refund") await aiUsageRepository.refund(user.id, String(body.reservationId)); else await aiUsageRepository.complete(user.id, String(body.reservationId), { promptChars: Number(body.promptChars ?? 0), responseChars: Number(body.responseChars ?? 0), model: "gemini-3.5-flash" }); return NextResponse.json({ ok: true }); } return NextResponse.json({ error: "Ação inválida." }, { status: 400 }); } catch (error) { if (error instanceof Error && error.message === "AI_QUOTA_EXCEEDED") return NextResponse.json({ error: "Você atingiu o limite de 5 análises nesta semana." }, { status: 429 }); throw error; } }
