import { FieldValue, Timestamp } from "firebase-admin/firestore";
import type { CommunicationRepository } from "@/application/ports/communication-repository";
import type { Communication, CommunicationAudience, CommunicationChannel } from "@/domain/communication/entities";
import { adminFirestore } from "@/infrastructure/firebase/admin";

function date(value: unknown) { return value instanceof Timestamp ? value.toDate() : null; }
function communication(id: string, data: FirebaseFirestore.DocumentData): Communication { return { id, title: String(data.title ?? ""), content: String(data.content ?? ""), channel: data.channel as CommunicationChannel, audience: data.audience as CommunicationAudience, status: data.status ?? "draft", scheduledAt: date(data.scheduledAt), createdAt: date(data.createdAt), sentAt: date(data.sentAt), createdBy: String(data.createdBy ?? ""), recipientCount: Number(data.recipientCount ?? 0), failureReason: String(data.failureReason ?? "") }; }

export class FirebaseCommunicationRepository implements CommunicationRepository {
  private db = adminFirestore();
  async list(limit = 50) { const snapshot = await this.db.collection("communications").limit(200).get(); return snapshot.docs.map((item) => communication(item.id, item.data())).sort((left, right) => (right.createdAt?.getTime() ?? 0) - (left.createdAt?.getTime() ?? 0)).slice(0, limit); }
  async listDue(now: Date) { const snapshot = await this.db.collection("communications").where("status", "==", "scheduled").get(); return snapshot.docs.map((item) => communication(item.id, item.data())).filter((item) => item.scheduledAt && item.scheduledAt <= now); }
  async create(input: { title: string; content: string; channel: CommunicationChannel; audience: CommunicationAudience; scheduledAt: Date | null; createdBy: string }) { const ref = this.db.collection("communications").doc(); await ref.set({ ...input, status: input.scheduledAt ? "scheduled" : "draft", createdAt: FieldValue.serverTimestamp(), sentAt: null, recipientCount: 0, failureReason: "" }); return communication(ref.id, { ...input, status: input.scheduledAt ? "scheduled" : "draft", createdAt: new Date(), sentAt: null, recipientCount: 0, failureReason: "" }); }
  async updateStatus(id: string, status: Communication["status"], details: { sentAt?: Date | null; failureReason?: string; recipientCount?: number } = {}) { await this.db.collection("communications").doc(id).set({ status, ...details, ...(details.sentAt ? { sentAt: Timestamp.fromDate(details.sentAt) } : {}), updatedAt: FieldValue.serverTimestamp() }, { merge: true }); }
  async createInternalDeliveries(communicationId: string, userIds: string[]) { const batch = this.db.batch(); for (const userId of userIds) batch.set(this.db.collection("communicationDeliveries").doc(`${communicationId}_${userId}`), { communicationId, userId, channel: "internal", status: "sent", createdAt: FieldValue.serverTimestamp(), deliveredAt: FieldValue.serverTimestamp(), openedAt: null }); await batch.commit(); }
  async listUserDeliveries(userId: string, limit = 50) { const snapshot = await this.db.collection("communicationDeliveries").where("userId", "==", userId).limit(200).get(); const rows = await Promise.all(snapshot.docs.filter((item) => item.data().channel === "internal").map(async (item) => { const data = item.data(); const parent = await this.db.collection("communications").doc(String(data.communicationId)).get(); const communicationData = parent.data() ?? {}; return { id: item.id, communicationId: String(data.communicationId), title: String(communicationData.title ?? ""), content: String(communicationData.content ?? ""), status: String(data.status ?? "sent"), createdAt: date(communicationData.createdAt), openedAt: date(data.openedAt) }; })); return rows.sort((left, right) => (right.createdAt?.getTime() ?? 0) - (left.createdAt?.getTime() ?? 0)).slice(0, limit); }
  async countUnreadDeliveries(userId: string) { const snapshot = await this.db.collection("communicationDeliveries").where("userId", "==", userId).limit(200).get(); return snapshot.docs.filter((item) => item.data().channel === "internal" && !item.data().openedAt && item.data().status !== "opened").length; }
  async markDeliveryOpened(deliveryId: string, userId: string) { const ref = this.db.collection("communicationDeliveries").doc(deliveryId); const snapshot = await ref.get(); if (!snapshot.exists || snapshot.data()?.userId !== userId) throw new Error("Aviso inválido."); await ref.set({ status: "opened", openedAt: FieldValue.serverTimestamp() }, { merge: true }); }
  async deleteDelivery(deliveryId: string, userId: string) { const ref = this.db.collection("communicationDeliveries").doc(deliveryId); const snapshot = await ref.get(); if (!snapshot.exists || snapshot.data()?.userId !== userId) throw new Error("Aviso inválido."); await ref.delete(); }
}

export const communicationRepository = new FirebaseCommunicationRepository();
